"""Added initial table for episode

Revision ID: 06e1939cead6
Revises: 261512d5ff5f
Create Date: 2022-05-19 11:14:43.082723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e1939cead6'
down_revision = '261512d5ff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('states', sa.String(), nullable=False),
    sa.Column('predicted_offer_1', sa.String(), nullable=False),
    sa.Column('predicted_offer_2', sa.String(), nullable=True),
    sa.Column('predicted_offer_3', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('up_to_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_customer_id'), 'episode', ['customer_id'], unique=False)
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_last_update'), 'episode', ['last_update'], unique=False)
    op.create_index(op.f('ix_episode_predicted_offer_1'), 'episode', ['predicted_offer_1'], unique=False)
    op.create_index(op.f('ix_episode_predicted_offer_2'), 'episode', ['predicted_offer_2'], unique=False)
    op.create_index(op.f('ix_episode_predicted_offer_3'), 'episode', ['predicted_offer_3'], unique=False)
    op.create_index(op.f('ix_episode_states'), 'episode', ['states'], unique=False)
    op.create_index(op.f('ix_episode_up_to_date'), 'episode', ['up_to_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_up_to_date'), table_name='episode')
    op.drop_index(op.f('ix_episode_states'), table_name='episode')
    op.drop_index(op.f('ix_episode_predicted_offer_3'), table_name='episode')
    op.drop_index(op.f('ix_episode_predicted_offer_2'), table_name='episode')
    op.drop_index(op.f('ix_episode_predicted_offer_1'), table_name='episode')
    op.drop_index(op.f('ix_episode_last_update'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_customer_id'), table_name='episode')
    op.drop_table('episode')
    # ### end Alembic commands ###
