"""Added agent

Revision ID: 261512d5ff5f
Revises: 7c23e8412e6c
Create Date: 2022-05-16 01:32:26.061502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261512d5ff5f'
down_revision = '7c23e8412e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_last_update'), 'agent', ['last_update'], unique=False)
    op.create_index(op.f('ix_agent_version'), 'agent', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_version'), table_name='agent')
    op.drop_index(op.f('ix_agent_last_update'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
