"""Added initial table for product

Revision ID: 950cae99d9d2
Revises: a84c5aaa7403
Create Date: 2022-05-19 11:18:50.849647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950cae99d9d2'
down_revision = 'a84c5aaa7403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_offer_id'), 'product', ['offer_id'], unique=False)
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_offer_id'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
