"""Added initial table for reward

Revision ID: a84c5aaa7403
Revises: 06e1939cead6
Create Date: 2022-05-19 11:17:20.207083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84c5aaa7403'
down_revision = '06e1939cead6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('accepted_offer', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('up_to_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_accepted_offer'), 'reward', ['accepted_offer'], unique=False)
    op.create_index(op.f('ix_reward_customer_id'), 'reward', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reward_id'), 'reward', ['id'], unique=False)
    op.create_index(op.f('ix_reward_last_update'), 'reward', ['last_update'], unique=False)
    op.create_index(op.f('ix_reward_up_to_date'), 'reward', ['up_to_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_up_to_date'), table_name='reward')
    op.drop_index(op.f('ix_reward_last_update'), table_name='reward')
    op.drop_index(op.f('ix_reward_id'), table_name='reward')
    op.drop_index(op.f('ix_reward_customer_id'), table_name='reward')
    op.drop_index(op.f('ix_reward_accepted_offer'), table_name='reward')
    op.drop_table('reward')
    # ### end Alembic commands ###
